### ISSUE TITLE
CamperBot's code format help link broken

### ISSUE THREAD

**Issue by chautob0t** [FreeCodeCamp/camperbot#10]
In the Gitter application, when I tried to paste a code, CamperBot's help link is this - 
https://github.com/freecodecamp/freecodecamp/wiki/code-formatting
![camper](https://cloud.githubusercontent.com/assets/8208082/11245469/ed57a490-8e38-11e5-886c-c6ab95108e80.PNG)

This should be changed to this - https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-format

**Comment by bugron** [comment]
Closed via https://github.com/FreeCodeCamp/wiki/pull/130.
