### ISSUE TITLE
Camper bot - Wiki Migration

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/camperbot#103]
As discussed earlier with @Rafase282 in the chat:

Camperbot will no longer be able to suggest any of the wiki articles including:
1. Solution hints
2. Rooms
3. Articles
4. Any other help topic

Hence the course of action is now to:
- [x] Close all the open issues are pull requests with after a thorough audit.
- [ ] Fix any issues relevant to chat and clean up this repository of the wiki related logic.
- [x] If it receives any command for wiki, respond with a migration message.
- [ ] Deploy the bot.

**Note : Its functionality to thank people will remain as such.** 
But any relevant help links should be removed or changed to forum links if available

/cc @FreeCodeCamp/issue-moderators  
Refer https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9731

**Comment by JasonXiao2007** [comment]
what do you mean he no longer works?

**Comment by abhisekp** [comment]
@JasonXiao2007 the wiki has been moved to https://forum.freecodecamp.com and Dear @camperbot :alien: shouldn't and is unable to fetch from FreeCodeCamp repository wiki https://github.com/FreeCodeCamp/FreeCodeCamp/wiki as it has been disabled.

**Comment by JohnTendik** [comment]
@abhisekp Hey, on the gitter chat, the bot responds with "no entry" for every help command. Instead of that "no entry for whatever" text, would it make sense to display an updated text which reads:

"the wiki has been moved to https://forum.freecodecamp.com"

Just a suggestion. :)

**Comment by QuincyLarson** [comment]
@JohnTendik yes - I think that will be better. Even better would be for the wiki could pull from the forum. Here's an example forum API endpoint: https://forum.freecodecamp.com/c/wiki.json

**Comment by BerkeleyTrue** [comment]
Should this still be open?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I think we can close this. Later we can incorporate the new wiki articles into CamperBot but for now we've removed the deprecated wiki from it.
