### ISSUE TITLE
'help me' issue

### ISSUE THREAD

**Issue by diomed** [FreeCodeCamp/camperbot#105]
words: 

help me

trigger  adding environment variables [wiki]
which is obvious error. please fix that, it's annoying how much time we have to see this window
![help_me](https://cloud.githubusercontent.com/assets/72777/17638222/eab041f6-60e8-11e6-83d4-9bf5809d9d0a.png)

**Comment by abhisekp** [comment]
Fixing https://github.com/FreeCodeCamp/camperbot/issues/100 will fix this

**Comment by diomed** [comment]
also, 
phrases such as : 

help me pls and help me please

trigger camperbot to unnecessary answer 
_no wiki entry for: me pls_

which is really annoying

**Comment by raisedadead** [comment]
Closing in favor of #100
