### ISSUE TITLE
Camperbot fails to give points if there is a bracket before a "thanks"

### ISSUE THREAD

**Issue by tf2manu994** [freeCodeCamp/camperbot#112]
https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=57edcc09d56b91170dfc75cd

**Comment by ltegman** [comment]
Looks like now we're expecting a whitespace character on either side of the thanks but we really just need a non-word character.

**Comment by Dave1089** [comment]
adding `|\W` to first capturing group in [this line](https://github.com/FreeCodeCamp/camperbot/blob/6013edabcb34159501270cce4fec5b2f64f76133/data/rooms/RoomMessages.js#L48) will fix it I think

**Comment by abhisekp** [comment]
word breaks created a lot of problems. Please don't use `\W` or `\b`

**Comment by Dave1089** [comment]
@abhisekp just curiosity , how would using non-word metacharacter create problems?

**Comment by abhisekp** [comment]
@Dave1089 You may check the history https://github.com/FreeCodeCamp/camperbot/commits/6013edabcb34159501270cce4fec5b2f64f76133/data/rooms/RoomMessages.js

Previously, the regex was using `\b` which had many false positives leading to falsely giving out points to known and unknown campers (*unintended*). https://github.com/FreeCodeCamp/camperbot/commit/94e2558e94720dcb28417db33aa3ecc6f7bde2c9#diff-df3e5eba3a8c0d8a1bc5b0899e09041a

I fear the regex in the PR https://github.com/Dave1089/camperbot/pull/1/files#diff-df3e5eba3a8c0d8a1bc5b0899e09041aR48 might create the same issues.

**Comment by Dave1089** [comment]
@abhisekp I would like to get input from you how we should approach this issue of not validating non-word characters then

**Comment by abhisekp** [comment]
@Dave1089 I suggest to not complicate the regex more than it already is.
Using anything other than whitespace is not so common case. There might be more false positives if any character other than a whitespace is used.

**Comment by Dave1089** [comment]
Okey

**Comment by dhcodes** [comment]
Closing as stale and possible wontfix
