### ISSUE TITLE
Disable Camperbot greeting or make it less frequent

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/camperbot#117]
I worry that CamperBot's greetings - which get kind of old - are also deterring campers from greeting new campers. 

Could we turn this off and see how people react to it, and see whether it increases the likelihood of a human greeting?

Perhaps we could make CamperBot smarter, so if someone says "Hello World" it waits 30 seconds to see if anyone greets the newcomer before attempting to greet them itself?

Here's what the main chatroom looks like as I type this:

![](https://www.evernote.com/l/Ar_6RdCOf1ZEJrbd-nREjZ3ZKd03i52W_V0B/image.png)

**Comment by Jeff-Shapiro** [comment]
on top of that. I think using camperbot to send a PM supplying links and information on how to paste formatted code and the likes, the code of conduct reminder. It is also a good opportunity to remind the member to search and not just ask for a solution.

**Comment by QuincyLarson** [comment]
@Jeff-Shapiro these are good suggestions. Could you create a draft of the copy you think we should send to new campers? We want to strike a balance between giving them vital information and burying them in new information at a time when they're still getting their bearings on FCC in general.

**Comment by Jeff-Shapiro** [comment]
Good point maybe amend the structure of a wiki page to be a chatters guide linking out to the existing wikis.

**Comment by Jeff-Shapiro** [comment]
This is what Robert Richey wrote and its almost on par as to what I think should be sent out as a PM. Just add the code of conduct onto it. Its really neat and not heaps
![image](https://cloud.githubusercontent.com/assets/20011187/20467435/e7dcb814-afdb-11e6-8a0f-0dcb7dbf63ec.png)

**Comment by QuincyLarson** [comment]
@ltegman what are your thoughts on this?

**Comment by ltegman** [comment]
I really dig both these changes. I've thought for a while that the Camperbot greeting was hampering real human greetings. I should have some time over the long weekend to implement these changes, but I'd also be happy for anyone else who has the time to take a crack at it if they want :)

**Comment by QuincyLarson** [comment]
@ltegman awesome! Yes, I think turning greeting off completely for now and sending a message to the camper through CamperBot like the one Jeff suggested is a good idea, except instead of sending them links, I think we should send the following message:

### 🚀  Welcome to Free Code Camp's chat rooms on Gitter 🤖 

Free Code Camp is a friendly place to learn to code. We’re committed to keeping it that way. 

Be nice. Be helpful. And please read and abide by our [Code of Conduct](https://www.freecodecamp.com/code-of-conduct).

Here are some of our official chat rooms:
- [FreeCodeCamp](https://gitter.im/freecodecamp/FreeCodeCamp) - our main chat room - hang out and chat about life and learning to code
- [Help](https://gitter.im/freecodecamp/Help) - get coding help from your fellow campers 
- [CodeReview](https://gitter.im/freecodecamp/CodeReview) - give and receive constructive feedback from your fellow campers on your projects 
- [YouCanDoThis](https://gitter.im/freecodecamp/YouCanDoThis) - learning to code is hard - share your feelings and get moral support here 
- [CodingJobs](https://gitter.im/FreeCodeCamp/CodingJobs) - chat about the process of getting a coding job, such as portfolios, networking, and interviewing
- [Casual](https://gitter.im/freecodecamp/Casual) - you can chat about your non-coding interests with other campers here 
- [Contributors](https://gitter.im/freecodecamp/Contributors) - help us improve our open source platform and curriculum

**Comment by QuincyLarson** [comment]
@ltegman did you ever get a chance to look into this?

**Comment by diomed** [comment]
please kill command ` /rollem` because people spam with it , and it only shows rickroll video anyway

**Comment by t3h2mas** [comment]
@diomed please make a separate issue for your feature request

**Comment by QuincyLarson** [comment]
@ltegman any updates on this? 

Would anyone else be interested in taking a crack at this?

**Comment by raisedadead** [comment]
@QuincyLarson I have disabled the command completely via https://github.com/freeCodeCamp/camperbot/pull/125

Do we need to update the welcome to as suggested above? If yes, should this be a DM?

**Comment by raisedadead** [comment]
I am unaware of the discussion that went earlier and seems that the comments have been deleted from the thread.

**Comment by t3h2mas** [comment]
I think moving to a DM would be beneficial by
* keeping the public channels clean
* providing more information to the user

**Comment by raisedadead** [comment]
Yup, makes sense.
