### ISSUE TITLE
remove /rollem

### ISSUE THREAD

**Issue by diomed** [freeCodeCamp/camperbot#118]
please kill command `/rollem` because people spam with it , and it only shows rickroll video anyway.

**Comment by smileytechguy** [comment]
no

**Comment by smileytechguy** [comment]
What should be done instead is:

> @username: [check it out](the evil video)

just like i did to @diomed in chat

**Comment by Manish-Giri** [comment]
+1 for removing it.

**Comment by smileytechguy** [comment]
If we use the markdown above, it wont spam with the embed

**Comment by atjonathan** [comment]
Looks like we should remove this 👍

**Comment by t3h2mas** [comment]
If someone wants to jump in on this, feel free to notify/@ me with any questions.

**Comment by smileytechguy** [comment]
nooo

**Comment by Manish-Giri** [comment]
@t3h2mas Thanks! I'll take this one up..

**Comment by texas2010** [comment]
@Manish-Giri, are you still work on this?

**Comment by Manish-Giri** [comment]
@texas2010 I was told in the help chat that `rollem` was already removed, so I didn't come back to this issue. But looks like that was wrong information, I'll get to it now.

**Comment by texas2010** [comment]
@Manish-Giri, no problem.

have fun!
