### ISSUE TITLE
Add more 'thank you' phrases as as camperbot trigger words

### ISSUE THREAD

**Issue by diomed** [freeCodeCamp/camperbot#119]
Much people say **tnx** 

I suggest adding it as trigger word for giving cookies,
since there are many other variations that do that, tx being one of them.

This 1 you probably forgot.

**Comment by Margaret2** [comment]
I agree that tnx should be added, a lot of people say it. Also, now that all the language-specific rooms have been closed, it might be a good idea to add some words for thanks in other common languages, e.g. merci, gracias, and 谢谢.

**Comment by diomed** [comment]
also this variation doesn't seem to work:

**...thanks**

**Comment by OFFLlNE** [comment]
Any1 is working on that? I would like to try to do that

**Comment by t3h2mas** [comment]
@OFFLlNE it looks like it is up for grabs

Let me know if you need any help.

**Comment by Margaret2** [comment]
@OFFLlNE I was looking at it earlier, glad to let you try it though 😋 The regex for it is [here](https://github.com/freeCodeCamp/camperbot/blob/aa0115e0a4b98939d9339b13b5ab7f6c81e0deae/data/rooms/RoomMessages.js#L49), just so you don't have to hunt through the code to find it. Good luck! 🍀
