### ISSUE TITLE
Brownie Points bug: placing dots before 'Thanks' has no effect

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/camperbot#120]
I've noticed on several occasions, if a camper places dots before `Thanks`, this does not trigger Camperbot. An example - 

> Ah, just realize  what I should do....Thanks @xyzzzz

**Comment by diomed** [comment]
Also doesn't work when comma is in front  ` ,thanks @Manish-Giri ` 😈

**Comment by Manish-Giri** [comment]
I'd like to work on this, just seeing the "Help wanted" tag...

**Comment by dhcodes** [comment]
@Manish-Giri I think this would be where you improve the regex: https://github.com/freeCodeCamp/camperbot/blob/aa0115e0a4b98939d9339b13b5ab7f6c81e0deae/data/rooms/RoomMessages.js#L49

**Comment by Manish-Giri** [comment]
@dhcodes oops, I forgot to write `closes #xxxxx` on the PR. Could you close this issue pls?

**Comment by dhcodes** [comment]
👍
