### ISSUE TITLE
remove about

### ISSUE THREAD

**Issue by diomed** [freeCodeCamp/camperbot#122]
Upon mentioning word **about** 

camperbot displays spammy useless message saying:

' you need to ask about @someone! '

this should be removed.

**Comment by QuincyLarson** [comment]
I agree - this shouldn't trigger unless it has a target.

**Comment by Manish-Giri** [comment]
I'll take this up, would need some setup to get camperbot running locally, but it should also help with #120.

**Comment by QuincyLarson** [comment]
@Manish-Giri awesome - thanks for helping with this.
