### ISSUE TITLE
remove echo

### ISSUE THREAD

**Issue by diomed** [freeCodeCamp/camperbot#123]
again, another useless option that people just use to spam in chat, by repeating other people's sentences.

**Comment by OFFLlNE** [comment]
Seems like this is done https://github.com/freeCodeCamp/camperbot/pull/121

**Comment by OFFLlNE** [comment]
#121 was actually changes to echo, so I am reopening this issue, maybe this thing should be removed overall

**Comment by dhcodes** [comment]
PR submitted for this.
