### ISSUE TITLE
Fix "arigatou" too "arigato" (Thank you in Japanese) 

### ISSUE THREAD

**Issue by Azbo400** [freeCodeCamp/camperbot#137]
Hello, everyone!

Over on the freeCodeCamp main chat people noticed that "arigatou" is not supposed have "u" at the end, so I am proposing to fix that.

If you guys don't mind if I fix it myself, I think that would be a good first contribution to the freeCodeCamp community. 

Disclaimers:
1. Arigatou and Arigato **both** work, so maybe we want to keep that the same on purpose so either would work for anyone
2. I do not speak Japanese, @Manish-Giri noticed it, and let me go ahead and create an issue for it rather than him doing that.

Thank you very much!

**Comment by dhcodes** [comment]
Seems that arigatou is the written form and arigato is the spoken/pronunciation form. Since both are allowed by the bot, I think we can close this.
