### ISSUE TITLE
Should allow issue numbers without comment

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/camperbot#143]
Currently CamperBot will protest if a camper creates a pull request with an issue number in it. 

This is a common practice and should be allowed. We need to remove this functionality from CamperBot.

**Comment by erictleung** [comment]
To clarify, the commitizen allows commit message bodies to have issue numbers, but not in the title. So CamperBot should also allow that as well.

**Comment by QuincyLarson** [comment]
@erictleung Does CamperBot currently not allow issue numbers in the body of the commit? If that's the case, yes - we should allow commit messages in the body, but not the title, like Commitizen allows.

**Comment by QuincyLarson** [comment]
I should have opened this PR on https://github.com/freeCodeCamp/camper-gh-bot instead so I'm closing it here.
