### ISSUE TITLE
Use github api to update wiki articles

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/camperbot#17]

**Comment by SaintPeter** [comment]
Ref:
Webhooks, Push Event: https://developer.github.com/v3/activity/events/types/#pushevent
Guide:  https://developer.github.com/guides/delivering-deployments/

It looks like we can even get GitHub to send a "secret", which can be compared against a server environment variable.  

This looks really straightforward.

**Comment by raisedadead** [comment]
Closing as a wontfix.
Refer : https://github.com/FreeCodeCamp/camperbot/issues/103
