### ISSUE TITLE
Duplicate messages when command is entered by 2 users at once.

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/camperbot#22]
The following happens when two campers call up the code formatting wiki article at the same time (a common occurrence when someone doesn't format their code with markdown).
![_freecodecamp_freecodecamp_-_gitter](https://cloud.githubusercontent.com/assets/1381313/11513949/e226651a-982a-11e5-9a8a-3cbc97628c63.png)

**Comment by MaXwellFalstein** [comment]
One way to fix this could be to run a counter for one minute where an explain command is used, Camperbot will not post after the first instance.

**Comment by abhisekp** [comment]
@MaXwellFalstein a `debounce` function for that command for a minute.

**Comment by MaXwellFalstein** [comment]
@abhisekp yes, a ``` debounce ``` function would be good.

**Comment by abhisekp** [comment]
@MaXwellFalstein here is another issue related to this https://github.com/FreeCodeCamp/camperbot/issues/9

Lodash has a `_.debounce` function which can be used here, i guess.

**Comment by raisedadead** [comment]
Closing as a wontfix
https://github.com/FreeCodeCamp/camperbot/issues/103
