### ISSUE TITLE
Explain fails for staticReplies

### ISSUE THREAD

**Issue by duffn** [FreeCodeCamp/camperbot#24]
Trying to `explain` items in the [staticReplies](https://github.com/FreeCodeCamp/camperbot/blob/cc2d0814a76e6952db791dd1be2ee297584edabc/nap/lib/bot/KBase.js#L32) array fails with [`tried to linkify an empty item`](https://github.com/FreeCodeCamp/camperbot/blob/cc2d0814a76e6952db791dd1be2ee297584edabc/nap/lib/utils/Utils.js#L157) because there is no `dashedName` property, so the bot sends this:

<img width="176" alt="screen shot 2015-12-02 at 11 06 07 am" src="https://cloud.githubusercontent.com/assets/3457341/11539609/31a6994c-98e5-11e5-8c37-a03b81e163c9.png">

Regular wiki item `explain js closures`
```js
topicData {
  displayName: 'js closures',
  fileName: 'js-closures.md',
  data: 'example',
  dashedName: 'js-closures' }
Utils.linkify> link [js closures  [wiki]](https://github.com/freecodecamp/freecodecamp/wiki/js-closures)
Utils.linkify> link [read more about js closures on the FCC Wiki](https://github.com/freecodecamp/freecodecamp/wiki/js-closures)
GBot> out|  ## :point_right: [js closures  [wiki]](https://github.com/freecodecamp/freecodecamp/wiki/js-closures)
Closures are functions that refer to independent (free) variables. In other words, the function defined in the closure 'remembers' the environment in which it was created.
> tags: closure, javascript, js
:pencil: [read more about js closures on the FCC Wiki](https://github.com/freecodecamp/freecodecamp/wiki/js-closures)
```

staticReplies wiki item `explain link`
```js
topicData try this [guide](http://www.freecodecamp.com/field-guide/all-articles).
```

I can try to take this one, but need feedback on how to handle. Link to the wiki home page for these, change how these are handled and not link to anything, something else?

**Comment by dcsan** [comment]
maybe just remove staticReplies ? those should be mostly for commands, not content that could be in the wiki. i think i originally just hardcoded some replies in to bootstrap development.

**Comment by duffn** [comment]
Great, I'll take care of that.
