### ISSUE TITLE
User not found error message wording

### ISSUE THREAD

**Issue by duffn** [freeCodeCamp/camperbot#26]
The bot currently says "could not find receiver for user". It should provide a better worded error message when it can't find a user for brownie points.

<img width="853" alt="screen shot 2015-12-04 at 2 23 15 pm" src="https://cloud.githubusercontent.com/assets/3457341/11603251/bdcbcd48-9a9d-11e5-8345-abc5e6423345.png">

**Comment by SaintPeter** [comment]
A better message might be "Username not connected to GitHub Account" maybe with a link to a Wiki article.

**Comment by BerkeleyTrue** [comment]
"Github account not link with Free Code Camp"?

**Comment by SaintPeter** [comment]
> :warning: @username's Github account not linked with Free Code Camp - [More Info]()

With the link being a link to a wiki article.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by abhisekp** [comment]
It's better to give a direct link to link FCC with Github http://freecodecamp.com/link/github

**Comment by anuragaryan** [comment]
I did grep on  "could not find receiver for" but didn't find anything similar. :astonished:

**Comment by BerkeleyTrue** [comment]
@anuragaryan Is returned from the FCC api

**Comment by anuragaryan** [comment]
@BerkeleyTrue so how'd one go about solving it? From the FreeCodeCamp repo?

**Comment by BerkeleyTrue** [comment]
You'll need to change the message sent by camperbot.

**Comment by pshweta13** [comment]
how to get these brownie points, the same message is showing to me.

**Comment by abhisekp** [comment]
@pshweta13 Try linking your Github account and FreeCodeCamp account http://freecodecamp.com/link/github

**Comment by pdurbin** [comment]
I just saw `:warning: could not find receiver for pdurbin` at https://gitter.im/FreeCodeCamp/HelpDataViz?at=582dba2e3f3946057ac90954 . Is this because I'm using https://irc.gitter.im ? This warning makes no sense. Can it be removed or reworded?
