### ISSUE TITLE
Free Code Camp style guide 

### ISSUE THREAD

**Issue by duffn** [FreeCodeCamp/camperbot#28]
The code in this repository should conform to the FCC style guide.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Free-Code-Camp-JavaScript-Style-Guide
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/.eslintrc

**Comment by ltegman** [comment]
This definitely needs to happen. Should probably come after #3 though so we have at least some fail-safe to make sure we're not breaking anything in the course of refactoring it.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by ltegman** [comment]
Finished this linting a while ago and must have forgot to close this.
