### ISSUE TITLE
In-Chat Wiki (approach) Floods View

### ISSUE THREAD

**Issue by qmikew1** [FreeCodeCamp/camperbot#33]
Camperbot's wiki invocation (via such commands as explain, help, etc.,) results in, potentially, large wiki pages that can contain: multiple lines, static (or dynamic gif) images and other media that disrupts the chat window (both on desktop/ and mobile platforms). Would it be possible to limit summary to 2-4 lines and provide the actual link to the wiki?

**Comment by abhisekp** [comment]
:+1:

**Comment by dcsan** [comment]
when i wrote this before, i trim it up to the first heading. but that means people need to know that, and always put a first heading near the start of the wiki entry.

i think i put a character cut off in there too, but sometimes that chopped off html in the middle of a tag, so it screwed up other markup. you'd need to be smarter about where you edit. maybe split the text on newlines and trim there?

**Comment by qmikew1** [comment]
That's a good point (about the cutoff of html) tags, I was thinking about the practicality of this (because, there would need to be a parallel styling change to wikis (and existing wikis (even with a bash script would be a PITA but doable) not sure there would be overall support to effort

**Comment by raisedadead** [comment]
Closing as a wontfix.
https://github.com/FreeCodeCamp/camperbot/issues/103
