### ISSUE TITLE
change wiki edit link

### ISSUE THREAD

**Issue by dcsan** [FreeCodeCamp/camperbot#43]
when you explain entries the footer edit link

![image](https://cloud.githubusercontent.com/assets/514002/12219941/6cb07378-b70d-11e5-86e6-6a8f2004104b.png)

goes here ->

https://github.com/freecodecamp/freecodecamp/wiki

eg
https://github.com/freecodecamp/freecodecamp/wiki/waypoint-bring-your-javascript-slot-machine-to-life

but maybe should go here?

https://github.com/freecodecamp/wiki

**Comment by MaXwellFalstein** [comment]
I think it should link to [FreeCodeCamp/Wiki](https://github.com/freecodecamp/wiki)

**Comment by brutalcrozt** [comment]
@dcsan i still confuse with the main usage/purpose of camperbot.

**Comment by abhisekp** [comment]
@brutalcrozt lets discuss about camperbot matters in [**`FreeCodeCamp/camperbot`**](https://gitter.im/FreeCodeCamp/camperbot)

**Comment by raisedadead** [comment]
Closing as a wontfix.
https://github.com/FreeCodeCamp/camperbot/issues/103
