### ISSUE TITLE
Specifically exclude the word `tax` from the "Thank You" Regex

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/camperbot#49]
Because this is just silly:
![image](https://cloud.githubusercontent.com/assets/553494/12379315/fab73f3a-bd0c-11e5-8470-76ec3e69e7c1.png)

**Comment by abhisekp** [comment]
@SaintPeter that regex needs fixing https://github.com/dcsan/gitterbot/issues/142

**Comment by SaintPeter** [comment]
@abhisekp I like your proposed Regex.  Give us a PR, please.

**Comment by abhisekp** [comment]
My proposed regex has a minor flaw. Sometimes it doesn't work well with a particular way of thanking as tested in [**`[GitterBotX/playground?at=560a]`**](https://gitter.im/GitterBotX/playground?at=560ae012674bf7062bd12ead). It needs to be re-written with proper regex. I'll update it with a better regex and file a PR or if anyone else is interested could take it.

**Comment by SaintPeter** [comment]
@abhisekp I think it's a great project for you.

Note:  It may be easiest to just try to permute the list of possible "thank you" variants and add them like:
`/\b(thx|thanks|thank|tx)\b/` 
rather than trying to get fancy.  It may not catch all possible "thank you", but it becomes a LOT easier to maintain.  If someone comes up with a new variant, they can just add it to the `|`ed list.

Here is a quick first pass:
https://regex101.com/r/hH5cN7/30

The only thing I'm not sure about is ignoring stuff inside the triple backtick blocks.  I'm thinking maybe a separate regex could be run to remove those blocks before testing with this regex?

**Comment by noncentz** [comment]
I had a go at it and added a few more tests, https://regex101.com/r/hH5cN7/31
