### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/camperbot#57]
Tests are passing and linting is good right now, so this should be a cinch to get set up. I'll play around with it tomorrow.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by BerkeleyTrue** [comment]
I can add it to travis. We'll need a travis.yaml file for it to run, though.

**Comment by BerkeleyTrue** [comment]
Done

**Comment by ltegman** [comment]
Thank you good sir!
