### ISSUE TITLE
Double "Thank you" ?

### ISSUE THREAD

**Issue by Nikitaw99** [FreeCodeCamp/camperbot#59]
# This happened in chat:
---
@rphares wrote:
> tax @darrylpargeter  @darrylpargeter  @darrylpargeter 

@camperbot responded:

> :star: 714 | @darrylpargeter | [http://www.freecodecamp.com/darrylpargeter](http://www.freecodecamp.com/darrylpargeter)
> :star: 714 | @darrylpargeter | [http://www.freecodecamp.com/darrylpargeter](http://www.freecodecamp.com/darrylpargeter)
> :star: 714 | @darrylpargeter | [http://www.freecodecamp.com/darrylpargeter](http://www.freecodecamp.com/darrylpargeter)

---

Bug? I don't know. But yeah, That is an easier way to spam in chat.
Please fix.

**Comment by ltegman** [comment]
Thanks for the reminder about this. I actually had a PR open to fix this on the old repo and forgot to bring it over to this one. I'll dig it up and open it against the new repo later today :smile:

**Comment by Nikitaw99** [comment]
@ltegman 
Alright! If possible, fix this:

---
@camperbot typed:
> :star: 58 | @medusalix | http://www.freecodecamp.com/medusalix
> nikitaw99 sends brownie points to @medusalix   

---
