### ISSUE TITLE
Update relative links to absolute links in chatrooms

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/camperbot#64]
Recently, we have made a switch to relative links in the FCC wiki. The links to other wiki articles, or fragmented links within same articles - are now relative. 

However, the content in the chatroom would require absolute links. We need to have camperbot parse the links before posting, and add a constant URL string ahead of all hyperlinks.

**Comment by alayek** [comment]
@Rafase282 @koustuvsinha @BerkeleyTrue @raisedadead  FYI

**Comment by Rafase282** [comment]
:+1:  This should be bumped in the priority queue.Who could I talk to so I can get some quick walk-through on how the bot work so I can try and get a fix?

**Comment by raisedadead** [comment]
As per a [comment](https://gitter.im/FreeCodeCamp/camperbot?at=56e432c6bb541ac77f4f08a9) by @abhisekp 

we need this:

https://github.com/FreeCodeCamp/camperbot/blob/master/lib/utils/TextLib.js#L5
```javascript
TextLib.fixRelativeLink = function fixRelativeLink(wikiContent, baseUrl = 'http://github.com/FreeCodeCamp/FreeCodeCamp/wiki/') {
    const linkMatchRegExp = /\[.+\]\((.+)\)/g; // @FIXME needs to check if relative url
    return wikiContent.replace(linkMatchRegExp, baseUrl + '$1');
}
```
and a call to it in https://github.com/FreeCodeCamp/camperbot/blob/master/lib/bot/KBase.js#L47
```javascript
TextLib.fixRelativeLink(subset);
```
to fix the links.

**Comment by Rafase282** [comment]
https://github.com/FreeCodeCamp/camperbot/pull/65
https://github.com/FreeCodeCamp/camperbot/pull/66

This are the changes as I though they should be, need feedback.
