### ISSUE TITLE
output from bot need to fix.

### ISSUE THREAD

**Issue by dwd2010** [FreeCodeCamp/camperbot#72]
When i type wiki no repeat.

somehow it got missed bottom \`\`\`.

![fce30ba4b2fe4ec223e2554ade731534](https://cloud.githubusercontent.com/assets/9701609/14067228/9d087764-f425-11e5-8cbc-f668f43a0e6c.png)

**Comment by SaintPeter** [comment]
This is a problem with the Wiki Article Itself:
https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-No-Repeats-Please.md

It is not formatted properly.  Please open an issue on the Wiki repo.

Thanks and Happy coding!

**Comment by abhisekp** [comment]
@SaintPeter this not wiki issue. This is the way camperbot display the output. It discards anything > 20 lines. Hence, the bot needs fixing. It must account for long sentences in a line and code blocks.

**Comment by abhisekp** [comment]
@SaintPeter although I agree the wiki must also be formatted according to the formatting guidelines. But the bot **also** needs fixing.

**Comment by SaintPeter** [comment]
Have you taken a look at that article?  It's a trainwreck.

The default for the Campbot is display up until the first `h2` (`##`) or some number of characters.  In a properly formatted article the first `h2` would be right up near the top.

At this point it will be a lot easier to fix the article than to come up with some solid logic for the camperbot.
