### ISSUE TITLE
Automatic notification of FCC Challenges of members in a Gitter Room

### ISSUE THREAD

**Issue by kgashok** [FreeCodeCamp/camperbot#75]
We created a Room on GITTER and three of us colleagues have been added to it. In the "Activity" section, we would like to be notified of each other's completion of FCC challenges **automatically**. Can a **"/notifyCompletion"** command be created for this requirement?

**Comment by SaintPeter** [comment]
Humm . . . I don't think so.  

The activity section is handled by Gitter integration's.  They can be hooked up to things like GitHub, etc.  In order for what you're describing to work, we would need to somehow host an API or streaming service and have Gitter support it.

I think the best you could do would be to drop a notification in the Gitter room and `@message` your collaborators.

**Comment by kgashok** [comment]
> we would need to somehow host an API or streaming service and have Gitter support it

That would be real cool! Imagine a scenario where a group of 20-30 might jointly be working on FCC challenges. It would help create momentum both in a physical/viritual campsite meet.

**Comment by SaintPeter** [comment]
I don't disagree, it would be cool.  It's just beyond the capabilities of Camperbot and Gitter at this moment.

**Comment by kgashok** [comment]
> It's just beyond the capabilities

It can be built, right? Or do you see a technical impossibility in customizing a new Bot to do what needs to get done?

**Comment by ltegman** [comment]
This isn't actually something in the realm of camperbot and not likely FCC in the near future. As has been mentioned this would require development of a streaming FCC api, which would likely place undue pressure on our infrastructure for minimal benefit, as well as require writing a custom integration for Gitter. Neither of these are within the scope of the camperbot project.

**Comment by kgashok** [comment]
Ok, got it. Thanks,
