### ISSUE TITLE
Camperbot is giving away points in unofficial rooms

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/camperbot#84]
https://gitter.im/FreeCodeCamp/Casual

I was given points in this chat room for hangouts and camperbot gave me points... please fix 

thanks,
Tommy

**Comment by SaintPeter** [comment]
/Casual is an official room and you can receive points in it.  Is that an issue?

**Comment by dwd2010** [comment]
I think that is not issue.  someone just say thanks to @tommygebru.  I dont see any issue with bot.

**Comment by dwd2010** [comment]
@tommygebru, you got point because someone say thank you to you. i hope you understand that is how you get a brownie point at the gitter.

**Comment by tommygebru** [comment]
LOL i have no problems with brownie points, but because it is a chat room,
and not directly a help room associated with FCC Lessons.... I thought it
was important to mention 😊
