### ISSUE TITLE
Improve the 'about' command

### ISSUE THREAD

**Issue by Nikitaw99** [FreeCodeCamp/camperbot#86]
I've got an idea: camperbot will use :star2: `:star2:` for `1000 brownies` and above.
#### Currently:
> :star: 2468 | @abhisekp | [http://www.freecodecamp.com/abhisekp](http://www.freecodecamp.com/abhisekp)

#### Improved:
> :star2: 2468 | @abhisekp | [http://www.freecodecamp.com/abhisekp](http://www.freecodecamp.com/abhisekp)

Add this whenever you want, this feature isn't necassary. But I still want it to be added.

**Comment by Nikitaw99** [comment]
To-do list for all your needs:
- [ ] Make `camperbot` find if a user has `1000 or more brownies`.
- [ ] Copy-paste :D

**Comment by Nikitaw99** [comment]
Sorry that I mentioned you, @abhisekp!

**Comment by SaintPeter** [comment]
This is a great idea and @abhisekp is just the man to work on it!

**Comment by Nikitaw99** [comment]
@SaintPeter Thanks! It just popped out of my head randomly :)
