### ISSUE TITLE
Explain Java

### ISSUE THREAD

**Issue by CEREBR4L** [FreeCodeCamp/camperbot#90]
When you know someone bring up the subject of my worst enemy (java) and I "cleverly" think "hmmm if I type explain java surely I will get a page telling this nice person about the horridness of java" but instead I got a page on javascript! 

This makes me very upset for two reasons: 
1. It made me look dumb (very bad time in my life). 
2. java != JavaScript 

It would be nice if we could do something about this atrocity. 

Love,
CEREBR4L

**Comment by abhisekp** [comment]
@CEREBR4L type `explain java_` (then a space)

**Comment by CEREBR4L** [comment]
@abhisekp I shall remember for the future though it would be nice if it was more simple.

**Comment by abhisekp** [comment]
@CEREBR4L Well, the take away is Java can't be explained :wink: :stuck_out_tongue_winking_eye:
