### ISSUE TITLE
Add duckduckgo Instant answer support

### ISSUE THREAD

**Issue by meetmangukiya** [FreeCodeCamp/camperbot#94]
This functionality will give superpowers to our dear @camperbot

**Comment by atjonathan** [comment]
cc/ @FreeCodeCamp/issue-moderators Do we want this to be a feature?

**Comment by AkiraLaine** [comment]
Wolfram Alpha would be better, but this would lead to the main chat being really spammed.

**Comment by meetmangukiya** [comment]
@AkiraLaine not if we enable camperbot to reply to every single person that starts a chat with it. Though I am not sure if it is feasible to do so

**Comment by atjonathan** [comment]
I personally don't see why we need this? The main chat is already spammed anyway.

**Comment by atjonathan** [comment]
@ltegman What are your thoughts :grey_question:

**Comment by ltegman** [comment]
@atjonathan I'm not a fan of features like this. It distracts and clutters an already busy chatroom. If someone really wants a feature like this they can make a bash script to do this for them in terminal. If there's programming related topics you'd like to have Camperbot tell you about you should add an article about it to the wiki :smile:
